### ISSUE TITLE
Impossible price false-negative

### ISSUE THREAD

**Issue by Nyconing** [artem6/acnh_turnips#1]
My turnips sells at 102 and the tanuki paid me 37 per turnip in monday morning.

**Comment by artem6** [comment]
Hi @Nyconing . Thanks for submitting the bug. I made a correction to the algorithm. Please let me know if it works for you. You will need to close out of the app completely and come back in to see the change. Your prices will be saved. Also, is this your first time buying turnips? The bug only shows up for first time turnip buyers.

**Comment by Nyconing** [comment]
https://artem6.github.io/acnh_turnips/

```
buy 102
mon 37  34
tue 117 87
wed 126 --
```
“This scenario doesn't seem possible. Is there a mistake in the prices?“
the error still reproducible.

**Comment by artem6** [comment]
![Screen Shot 2020-04-21 at 9 30 46 PM](https://user-images.githubusercontent.com/8940210/79940740-6b727980-8417-11ea-9e7c-728fbb72373f.png)

You should sell Wed PM for a price between 125 and 220. Try closing out of the turnip calculator page and opening it back up again. All the prices will remain saved. The app uses services workers so that it can work offline, but unfortunately that comes with the downside of not giving users the latest updates until they entirely close the app and open it again.
